### ISSUE TITLE
Captcha solved but wrong, Retrying...

### ISSUE THREAD

**Issue by iEventz** [DsCookieMaster/hcaptcha-solver#2]
Everytime I run this program it says "Captcha solved but wrong, Retrying...".. Is there anyway to fix this? And I'm not using any proxies.

**Comment by DsCookieMaster** [comment]
[ except hcaptcha.ApiError as e:
            #This is where the captcha fails. means its solved but wrong images are chosen
            Console.debug(f"[-] Captcha solved but wrong, Retrying...")](https://github.com/DsCookieMaster/hcaptcha-solver/blob/c3cff26bc30d941d4766e27ad5ab3d8fc1209c49/modules/captcha.py#L96)

It happens here, if you debug the code, set a breakpoint at result. You might notice that for some images even if question is "select a adult cat", the ai would return result true for "small cats" too.

I have already mentioned the issue with the AI solver in [references](https://github.com/DsCookieMaster/hcaptcha-solver#ai-captcha-solver-reference).

**Comment by DsCookieMaster** [comment]
As no more questions have been asked here, i ll close this issue..
