### ISSUE TITLE
discord detects the solved captcha and accounts is locked.

### ISSUE THREAD

**Issue by criminal38** [DsCookieMaster/hcaptcha-solver#3]
discord detects the solved captcha and accounts is locked

**Comment by DsCookieMaster** [comment]
would you like to provide a reference to the working captcha **or** a proof where you gathered this info ?

**Comment by DsCookieMaster** [comment]
@criminal38  has not replied back since 8 days. I ll clsoe this issue. Feel free to reach me out at discord or re-open this issue!
