### ISSUE TITLE
specific discord site-key not working

### ISSUE THREAD

**Issue by wlrd1337** [DsCookieMaster/hcaptcha-solver#5]
url: discord.com
site-key: f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34
got this site-key from: https://discord.com/oauth2/authorize?client_id=0&permissions=0

error: AI not trained for this captcha type yet !!!

other site-keys are working

**Comment by DsCookieMaster** [comment]
Since "http://" was missing, Can you try it with url: http://discord.com.

Also, could you share a **picture of the hcaptcha question** you get on this site:  https://discord.com/oauth2/authorize?client_id=0&permissions=0
