### ISSUE TITLE
70% Fail rate.

### ISSUE THREAD

**Issue by Godwhitelight** [DsCookieMaster/hcaptcha-solver#6]
Ok, I won't lie this is kinda epic. but u got a fail rate of about 70% which is really bommer.
Although you should try to fix it. I think it's the issue with the solving data or smth it's just really not trained enough.

**Comment by DsCookieMaster** [comment]
**Ok, I won't lie this is kinda epic:** 
### Thank you. 

**but u got a fail rate of about 70% which is really bommer:**
### try adding some proxies or debugging code, checking around whats going wrong each time, many people reached out to my discord straight, showed their screen on a video call and we were able to minimize that failing rate from 50+ to 20 or 30. In fact the time I was about to push this repo. I got a failing rate of 35 to 40.


**Although you should try to fix it: **
### i ll try to fix it after 9th November

**I think it's the issue with the solving data or smth it's just really not trained enough:** 
You should try to read the readme, you will find many answers to your doubts. First paragraph literally says how this repo was built.
