### ISSUE TITLE
Invalid captcha issue

### ISSUE THREAD

**Issue by fxyqq** [DsCookieMaster/hcaptcha-solver#7]
Invalid captcha {"captcha_key": ["invalid-response"], "captcha_sitekey": "4c672d35-0701-42b2-88c3-78380b0db560", "captcha_service": "hcaptcha"}

**Comment by DsCookieMaster** [comment]
What url and site key you entered?
Are you testing with proxy or without ?

Did you read the readme from start to end  and did all the installation steps?

**Comment by fxyqq** [comment]
4c672d35-0701-42b2-88c3-78380b0db560 - site key
discord.gg - url

tried it with both proxy and without

yes

**Comment by DsCookieMaster** [comment]
Works for me.
![image](https://user-images.githubusercontent.com/105941365/198789030-a6029bdb-990b-4407-9baa-62cd83f35b70.png)

Your url format is wrong. before you change a code atleast look at it how its written.

**Comment by fxyqq** [comment]
i meant to say discord.com

**Comment by DsCookieMaster** [comment]
Even in that case, your url **format** is wrong. 
Its a very simple issue. So i will not tell you directly, go and check the code in github and compare it with your modified version. You will be able to fix it.

If it worked put a star on this repo and reply here so i close this issue !!

**Comment by DsCookieMaster** [comment]
looks like he figured it out !
