### ISSUE TITLE
Always Wrong Return

### ISSUE THREAD

**Issue by seadhy** [DsCookieMaster/hcaptcha-solver#8]
It always returns an error, so I can't use it.
![image](https://user-images.githubusercontent.com/82868382/198889511-a7ea6f20-d51f-460d-9747-b59223ac38f1.png)

I'm trying through this site: https://accounts.hcaptcha.com/demo

**Comment by DsCookieMaster** [comment]
there is a beautiful lengthy readme, go through it !!

**Comment by seadhy** [comment]
I did everything you said. I modified chromedriver in its google version, put a quality proxy in it, downloaded models and modules.
